#!/bin/bash

#
# Generated by: Claude Code
# Date: 2025-10-19
# Purpose: Startup script for GenApp testing environment
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_PORT=8080
DB_PORT=5432
FRONTEND_PORT=3000
TIMEOUT=60
CHECK_INTERVAL=2

# Helper functions
print_header() {
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${YELLOW}ℹ${NC} $1"
}

print_divider() {
    echo -e "${BLUE}────────────────────────────────────────────────────────────${NC}"
}

# Check prerequisites
check_docker() {
    print_header "Checking Prerequisites"

    if ! command -v docker &> /dev/null; then
        print_error "Docker not found. Please install Docker."
        exit 1
    fi
    print_success "Docker is installed"

    # Check for docker compose (v2) or docker-compose (v1)
    if ! docker compose version &> /dev/null && ! command -v docker-compose &> /dev/null; then
        print_error "Docker Compose not found. Please install Docker Compose."
        exit 1
    fi
    print_success "Docker Compose is installed"

    # Set DOCKER_COMPOSE command
    if docker compose version &> /dev/null; then
        DOCKER_COMPOSE="docker compose"
    else
        DOCKER_COMPOSE="docker-compose"
    fi

    if ! docker ps &> /dev/null; then
        print_error "Docker daemon is not running. Please start Docker."
        exit 1
    fi
    print_success "Docker daemon is running"
}

# Start services
start_services() {
    print_header "Starting Services with Docker Compose"

    cd "$PROJECT_DIR"

    print_info "Pulling latest images..."
    $DOCKER_COMPOSE pull --quiet 2>/dev/null || true

    print_info "Starting PostgreSQL, Backend, and Frontend..."
    $DOCKER_COMPOSE up -d

    print_success "Services started (may still be initializing...)"
}

# Wait for service to be healthy
wait_for_service() {
    local service=$1
    local port=$2
    local name=$3
    local elapsed=0

    print_info "Waiting for $name on port $port..."

    while [ $elapsed -lt $TIMEOUT ]; do
        if nc -z localhost $port 2>/dev/null; then
            print_success "$name is ready"
            return 0
        fi

        sleep $CHECK_INTERVAL
        elapsed=$((elapsed + CHECK_INTERVAL))
        echo -ne "\r  Waiting... ${elapsed}s / ${TIMEOUT}s"
    done

    print_error "$name failed to start within ${TIMEOUT}s"
    return 1
}

# Check service health
check_service_health() {
    local url=$1
    local name=$2

    if curl -s "$url" > /dev/null 2>&1; then
        print_success "$name is healthy"
        return 0
    else
        print_error "$name health check failed"
        return 1
    fi
}

# Display service status
show_status() {
    print_header "Service Status"

    $DOCKER_COMPOSE ps
}

# Display endpoint information
show_endpoints() {
    print_header "Available Endpoints"

    echo ""
    echo -e "${GREEN}Frontend (React UI)${NC}"
    echo "  URL:     http://localhost:$FRONTEND_PORT"
    echo "  Status:  $(curl -s http://localhost:$FRONTEND_PORT > /dev/null 2>&1 && echo -e "${GREEN}✓ Running${NC}" || echo -e "${RED}✗ Not ready${NC}")"

    echo ""
    echo -e "${GREEN}Backend API${NC}"
    echo "  URL:     http://localhost:$BACKEND_PORT"
    echo "  Status:  $(curl -s http://localhost:$BACKEND_PORT/actuator/health > /dev/null 2>&1 && echo -e "${GREEN}✓ Running${NC}" || echo -e "${RED}✗ Not ready${NC}")"

    echo ""
    echo -e "${GREEN}Swagger UI (API Documentation & Testing)${NC}"
    echo "  URL:     http://localhost:$BACKEND_PORT/swagger-ui.html"
    echo "  Spec:    http://localhost:$BACKEND_PORT/v3/api-docs"

    echo ""
    echo -e "${GREEN}PostgreSQL Database${NC}"
    echo "  Host:    localhost:$DB_PORT"
    echo "  User:    genapp_user"
    echo "  Password: genapp_password"
    echo "  Database: genapp"
    echo ""
    echo "  Connect with: psql -h localhost -U genapp_user -d genapp"

    echo ""
}

# Show logs
show_logs() {
    print_header "Recent Logs"

    echo ""
    echo -e "${BLUE}Backend Logs (last 20 lines):${NC}"
    $DOCKER_COMPOSE logs --tail=20 backend | head -20

    echo ""
    echo -e "${BLUE}Database Logs (last 20 lines):${NC}"
    $DOCKER_COMPOSE logs --tail=20 postgres | head -20
}

# Test API endpoints
test_endpoints() {
    print_header "Testing API Endpoints"

    echo ""
    echo -e "${YELLOW}Testing GET /api/customers...${NC}"
    response=$(curl -s http://localhost:$BACKEND_PORT/api/customers)
    echo "Response: $response" | head -c 200
    echo "..."

    echo ""
    echo -e "${YELLOW}Testing GET /actuator/health...${NC}"
    curl -s http://localhost:$BACKEND_PORT/actuator/health | jq '.'
}

# Wait for all services
wait_for_all_services() {
    print_header "Waiting for Services to be Ready"

    # Wait for PostgreSQL
    wait_for_service "postgres" "$DB_PORT" "PostgreSQL" || return 1
    sleep 3  # Extra wait for DB to fully initialize

    # Wait for Backend
    wait_for_service "backend" "$BACKEND_PORT" "Backend API" || return 1

    # Wait for Frontend
    wait_for_service "frontend" "$FRONTEND_PORT" "Frontend" || return 1

    echo ""
    print_success "All services are ready!"
}

# Open browser
open_browser() {
    local url=$1
    local name=$2

    print_info "Opening $name in browser: $url"

    if [[ "$OSTYPE" == "darwin"* ]]; then
        open "$url"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if command -v xdg-open &> /dev/null; then
            xdg-open "$url"
        fi
    elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
        start "$url"
    fi
}

# Cleanup
cleanup() {
    print_header "Cleanup"
    print_info "To stop services: $DOCKER_COMPOSE down"
    print_info "To stop and remove data: $DOCKER_COMPOSE down -v"
}

# Main flow
main() {
    echo ""
    print_header "GenApp - Test Environment Startup"
    echo ""

    # Check prerequisites
    check_docker
    echo ""

    # Start services
    start_services
    echo ""

    # Wait for services
    wait_for_all_services
    echo ""

    # Show status
    show_status
    echo ""

    # Show endpoints
    show_endpoints

    # Test endpoints
    echo ""
    test_endpoints

    # Show logs
    echo ""
    echo -e "${BLUE}(Showing recent logs...)${NC}"
    show_logs

    # Offer to open browser
    print_divider
    echo ""
    read -p "Open Swagger UI in browser? (y/n) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        open_browser "http://localhost:$BACKEND_PORT/swagger-ui.html" "Swagger UI"
    fi

    echo ""
    echo -e "${GREEN}✓ GenApp is ready for testing!${NC}"
    echo ""

    cleanup
    echo ""
}

# Run main
main
